name: Validate Schemas

on:
  push:
    paths:
      - '**/*.yaml'
      - '**/*.yml'
      - '.schemas/**/*.json'
  pull_request:
    paths:
      - '**/*.yaml'
      - '**/*.yml'
      - '.schemas/**/*.json'

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4

      - id: set-matrix
        run: |
          PROJECTS=$(ls -d */ | grep -v '.git\|.github\|.schemas\|.vscode' | sed 's#/##')
          CONFIGS=("development" "hosting")
          MATRIX="{\"include\":["
          FIRST=true
          for project in $PROJECTS; do
            for config in "${CONFIGS[@]}"; do
              if [ "$FIRST" = true ]; then
                FIRST=false
              else
                MATRIX+=","
              fi
              MATRIX+="{\"project\":\"$project\",\"config\":\"$config\"}"
            done
          done
          MATRIX+="]}"
          echo "matrix=$MATRIX" >> $GITHUB_OUTPUT

  validate:
    needs: prepare
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.prepare.outputs.matrix)}}
    steps:
      - uses: actions/checkout@v4

      - uses: nrkno/yaml-schema-validator-github-action@v5.1.0
        with:
          schema: .schemas/${{ matrix.config }}.json
          target: ${{ matrix.project }}/${{ matrix.config }}.yaml
